### PR TITLE
Fix: update angular to beta.11

### PR DESCRIPTION
**Pull request by jamesjwarren**
angular2 changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta11-2016-03-18 

es6-shim update also fixes this error in console:
`Uncaught (in promise) TypeError: object is not a constructor`

### CODE REVIEW

**Comment by jamesjwarren** [comment]
@edwardoparearyee any ideas why this could be failing e2e tests?

**Comment by edwardoparearyee** [comment]
@jamesjwarren can you run the e2e tests locally?

**Comment by edwardoparearyee** [comment]
@jamesjwarren you also want to login to saucelabs and have a look at the tests being run, login details are on passpack.

**Comment by jamesjwarren** [comment]
@edwardoparearyee e2e passing now but travis is occassionaly failing to install phantomjs

**Pull request merged**
