### PR TITLE
Feature: End 2 End testing

### LINKED ISSUE #3: End to end testing

### PR DESCRIPTION
**Pull request by edwardoparearyee**
Adds e2e tests using protractor and saucelabs in a CI environment  

Fixes #3

### CODE REVIEW

**Comment by edwardoparearyee** [comment]
@jamesjwarren / @peeklondon this is ready now, pls take a :eyes:

**Comment by jamesjwarren** [comment]
@edwardoparearyee should we add the `npm run e2e` command to circle?

**Comment by edwardoparearyee** [comment]
@jamesjwarren we can do but at the moment travis runs the e2e tests on 5 browsers on both node versions plus it runs these e2e tests again for PR's making a total of 20 tests running in saucelabs at once. (we can only run 5 in parallel so the rest get queued).

Add circle to that and that would make it 30 tests trying to run simultaneously, I don't mind adding the e2e script to circle and commenting it out for when we are only using circle. Or maybe i could limit the amount of tests that travis runs so we could run saucelabs test via circle as well.

Thoughts?

**Comment by jamesjwarren** [comment]
Yeh I agree there isn't any point duplicating the running of tests, so just adding and commenting out is fine with me :+1:

**Comment by edwardoparearyee** [comment]
@jamesjwarren have added code to run e2e tests on circle but it is commented out for this project

**Pull request merged**
